name: Linting
on: push

permissions:
  contents: read

jobs:
  linting:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@d06fd9b3c0f44bc2878df5e4b3b8a2e8dbd2fe16 # ratchet:jdx/mise-action@v2
      - run: mise run check
